name = "vodi-panel"
main = "Source.js"
compatibility_date = "2026-09-24"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "vodi-independent-db"
database_id = "c0320bc5-f24e-4010-b6f6-5b93d92ca50f"
